### ISSUE TITLE
The version of the transformers

### ISSUE THREAD

**Issue by fiona-lxd** [OPTML-Group/QF-Attack#1]
What is the version of your transformers?

**Comment by zhmzm** [comment]
transformers >= 4.23.1

**Comment by fiona-lxd** [comment]
> transformers >= 4.23.1

Thank you very much for your quick response.  May I ask why the codes contains different embedding extractor functions, such as get_clip_embedding, get_text_embeds_without_uncond ? While I noticed that the first one gets clip text embeddings via "text_encoder.text_model.embeddings" and the latter one runs the whole procedure of text_encoder forward. Could you please tell us the reason behind this design?
