### ISSUE TITLE
New issues

### ISSUE THREAD

**Issue by JimmyChan-cyber** [OPTML-Group/QF-Attack#2]
I have upgrade the transformer's version. But 4.2x.x presents an error 'TypeError: CLIPTextTransformer._build_causal_attention_mask() missing 1 required positional argument: 'dtype'' after running the code. While higher version presents another error 'AttributeError: 'CLIPTextTransformer' object has no attribute '_build_causal_attention_mask''. So, the problem lies in PGD-ATTACK. Could you please check the code again and reply to me how to slove this problem if you don't mind? I'm looking forward to receive your reply.

**Comment by zhmzm** [comment]
Hi JimmyChan,

Did you install all libraries according to the requirements? It seems that some libraries change their implementation, which causes the error.

**Comment by JimmyChan-cyber** [comment]
Hi Haomin Zhuang,
    I have tried the best I could. I have tried transformer’s version from
4.25.0 to 4.42.4, still not working. Maybe such function have changed its
name.

zhmzm ***@***.***>于2024年8月27日 周二10:08写道：

**Comment by JimmyChan-cyber** [comment]
Hi Haomin Zhuang,
Is it convenient for you to talk with me about this issue on WeChat? If so,
please check my id 18118384250. I’m glad to receive your message.

JINMING CHEN ***@***.***>于2024年8月27日 周二10:16写道：

**Comment by zhmzm** [comment]
Hi Jimmy,

Thanks for your report. I fixed the issue.

https://github.com/OPTML-Group/QF-Attack/blob/06a9f83c3a61ef5f1a33f19139e57f5aabdf74ff/utils.py#L183-L224

Btw, it is unsafe to share your private information in the open-source community.

**Comment by JimmyChan-cyber** [comment]
Thanks for the feedback!

zhmzm ***@***.***>于2024年8月27日 周二11:57写道：

**Comment by JimmyChan-cyber** [comment]
Hi , I have downloaded your code. But the issue I mentioned last week still
exists. Could you please check it for me and tell me the solution? I’ll
appreciate that.

JINMING CHEN ***@***.***>于2024年8月27日 周二上午11:57写道：

**Comment by JimmyChan-cyber** [comment]
Which version should i upgrade the transformer?

JINMING CHEN ***@***.***>于2024年9月2日 周一上午11:40写道：

**Comment by JimmyChan-cyber** [comment]
Sorry my bad, it has been solved. Anyway thank you so much for helping me.

JINMING CHEN ***@***.***>于2024年9月2日 周一上午11:42写道：
